"""
Eppy-LLM: Natural-Language-Driven Building Energy Modeling
==========================================================

Module: parameter_modifier_tool.py
Agent 2 – Deterministic Modifier
--------------------------------
Applies rule-based, physically consistent parameter modifications to EnergyPlus IDF
models using Eppy. Supports automatic handling of different parameter types:

  • Continuous parameters → mid-range value  
  • Building orientation → cardinal angles  
  • Window geometry → vertex scaling (WWR adjustment)  
  • Categorical parameters → first suggested option  

Each modified IDF is saved to an output folder and logged for traceability.  
The tool also creates JSON and text summaries of changes.

Author: Huiwen Zhou  
Maintainer: @huiwenzhou  
"""

import os
import json
from copy import deepcopy
from eppy.modeleditor import IDF
from dotenv import load_dotenv
from datetime import datetime
import glob

# ✅ 1. Load .env for ENERGYPLUS_IDD_PATH
dotenv_path = os.path.join(os.path.dirname(__file__), "../../.env")
load_dotenv(dotenv_path)


def load_json_schema(schema_path: str) -> dict:
    """Load the parameter schema JSON generated by Agent 1."""
    with open(schema_path, "r", encoding="utf-8") as f:
        return json.load(f)


def find_latest_schema(output_dir: str) -> str:
    """Automatically find the latest JSON schema file."""
    json_files = glob.glob(os.path.join(output_dir, "parameter_schema_*.json"))
    if not json_files:
        raise FileNotFoundError("❌ No parameter_schema_*.json files found in outputs/")
    return max(json_files, key=os.path.getmtime)


def scale_window_vertices(obj, scale_factor: float):
    """
    Scale window vertices to change window size (for WWR adjustment).
    Keeps the window center position fixed and scales all vertices around it.
    
    Args:
        obj: eppy FenestrationSurface:Detailed object
        scale_factor: Scaling factor (0.7 = 70% size, 1.2 = 120% size)
    
    Returns:
        Modified object
    """
    try:
        # Get number of vertices
        num_vertices = int(obj.Number_of_Vertices)
        
        # Extract all vertices
        vertices = []
        for i in range(num_vertices):
            x = float(obj[f'Vertex_{i+1}_Xcoordinate'])
            y = float(obj[f'Vertex_{i+1}_Ycoordinate'])
            z = float(obj[f'Vertex_{i+1}_Zcoordinate'])
            vertices.append([x, y, z])
        
        # Calculate window center
        center_x = sum(v[0] for v in vertices) / num_vertices
        center_y = sum(v[1] for v in vertices) / num_vertices
        center_z = sum(v[2] for v in vertices) / num_vertices
        
        # Scale vertices around center
        for i, vertex in enumerate(vertices):
            # Vector from center to vertex
            dx = vertex[0] - center_x
            dy = vertex[1] - center_y
            dz = vertex[2] - center_z
            
            # Scale vector
            new_x = center_x + dx * scale_factor
            new_y = center_y + dy * scale_factor
            new_z = center_z + dz * scale_factor
            
            # Update vertex coordinates
            obj[f'Vertex_{i+1}_Xcoordinate'] = round(new_x, 6)
            obj[f'Vertex_{i+1}_Ycoordinate'] = round(new_y, 6)
            obj[f'Vertex_{i+1}_Zcoordinate'] = round(new_z, 6)
        
        return obj
    
    except Exception as e:
        print(f"      ⚠️ Warning: Could not scale vertices: {e}")
        return obj


def determine_parameter_type(info: dict) -> str:
    """
    Determine the type of parameter for smart rule selection.
    
    Returns:
        "orientation" | "window_geometry" | "continuous" | "categorical"
    """
    field = info.get("field", "").lower()
    idf_object = info.get("idf_object", "").upper()
    
    # Building orientation
    if idf_object == "BUILDING" and "north" in field and "axis" in field:
        return "orientation"
    
    # Window geometry (changed from "multiplier" to proper geometry scaling)
    if idf_object == "FENESTRATIONSURFACE:DETAILED":
        # If trying to modify multiplier, change to vertex scaling
        if "multiplier" in field:
            return "window_geometry"
        # Also detect if any vertex field is mentioned
        if "vertex" in field or "coordinate" in field:
            return "window_geometry"
    
    # Categorical (material names, construction names)
    original_value = info.get("original_value")
    if isinstance(original_value, str):
        return "categorical"
    
    # Default: continuous numeric parameter
    return "continuous"


def generate_modification_values(info: dict, param_type: str) -> list:
    """
    Generate modification values based on parameter type.
    
    Returns:
        List of (value, description) tuples
    """
    suggested_range = info.get("suggested_range", [])
    expected_effect = info.get("expected_effect", "adjust")
    original_value = info.get("original_value")
    
    # Type 1: Building Orientation
    if param_type == "orientation":
        if len(suggested_range) == 2:
            min_angle, max_angle = suggested_range
            # Generate cardinal directions within the suggested range
            candidates = [0, 90, 180, 270]
            valid_angles = [a for a in candidates if min_angle <= a <= max_angle]
            
            if not valid_angles:
                # If no cardinal direction in range, use range midpoint
                mid_angle = (min_angle + max_angle) / 2
                return [(mid_angle, f"Midpoint of suggested range [{min_angle}°, {max_angle}°]")]
            
            return [(angle, f"Cardinal direction {angle}°") for angle in valid_angles]
        else:
            # Default: all 4 cardinal directions
            return [(0, "North (0°)"), (90, "East (90°)"), (180, "South (180°)"), (270, "West (270°)")]
    
    # Type 2: Window Geometry (NEW: proper vertex scaling)
    elif param_type == "window_geometry":
        if expected_effect == "decrease":
            # Reduce window size: scale to 70%, 80%, 90%
            return [
                (0.7, "WWR reduction: Scale window to 70% of original size"),
                (0.8, "WWR reduction: Scale window to 80% of original size"),
                (0.9, "WWR reduction: Scale window to 90% of original size")
            ]
        elif expected_effect == "increase":
            # Increase window size: scale to 110%, 120%, 130%
            return [
                (1.1, "WWR increase: Scale window to 110% of original size"),
                (1.2, "WWR increase: Scale window to 120% of original size"),
                (1.3, "WWR increase: Scale window to 130% of original size")
            ]
        else:
            # Adjust: use middle value if range provided
            if len(suggested_range) == 2:
                mid_val = (suggested_range[0] + suggested_range[1]) / 2
                return [(mid_val, f"Scale window to {mid_val*100:.0f}% of original size")]
            else:
                return [(1.0, "Keep original size (no clear direction)")]
    
    # Type 3: Categorical (material/construction names)
    elif param_type == "categorical":
        if suggested_range and len(suggested_range) > 0:
            return [(suggested_range[0], "Using first suggested option")]
        else:
            return [(original_value, "No alternative provided, keeping original")]
    
    # Type 4: Continuous numeric parameters (default)
    else:
        if len(suggested_range) == 2:
            min_val, max_val = suggested_range
            mid_val = (min_val + max_val) / 2
            return [(mid_val, f"Midpoint of suggested range [{min_val}, {max_val}]")]
        else:
            # Fallback: 10% adjustment
            if expected_effect == "increase":
                return [(original_value * 1.1, "Increase by 10% (no range provided)")]
            elif expected_effect == "decrease":
                return [(original_value * 0.9, "Decrease by 10% (no range provided)")]
            else:
                return [(original_value, "No modification (insufficient information)")]


def modify_idf_smart_rules(idf_path: str, schema: dict, output_dir: str) -> list:
    """
    Apply smart rule-based modifications with parameter-type-specific strategies.
    NOW CORRECTLY HANDLES WINDOW GEOMETRY by scaling vertices instead of multiplier.
    """
    IDD_PATH = os.getenv("ENERGYPLUS_IDD_PATH", "")
    if not IDD_PATH:
        raise ValueError("ENERGYPLUS_IDD_PATH not set. Please export the path to Energy+.idd.")
    IDF.setiddname(IDD_PATH)
    
    base_idf = IDF(idf_path)
    os.makedirs(output_dir, exist_ok=True)
    modified_paths = []
    change_log = []

    parameters = schema.get("parameters_to_modify", {})
    if not parameters:
        print("⚠️ No parameters to modify found in schema.")
        return []

    print(f"🔧 Found {len(parameters)} parameters to modify using SMART RULES.\n")
    print("=" * 90)

    # ✅ Loop through parameters
    for param_name, info in parameters.items():
        idf_object_type = info.get("idf_object")
        target_object_name = info.get("object_name")
        field = info.get("field")
        category = info.get("category", "Unknown")
        original_value = info.get("original_value")
        
        print(f"\n📝 Processing: {param_name}")
        print(f"   Category: {category} | Object: {target_object_name} | Field: {field}")
        
        # ✅ Determine parameter type
        param_type = determine_parameter_type(info)
        print(f"   🧠 Parameter Type: {param_type.upper()}")
        
        # ✅ Generate modification values
        modifications = generate_modification_values(info, param_type)
        print(f"   📊 Generating {len(modifications)} variant(s):")
        
        # ✅ Create one IDF per modification value
        for idx, (new_value, description) in enumerate(modifications, 1):
            idf_copy = deepcopy(base_idf)
            objs = idf_copy.idfobjects.get(idf_object_type.upper(), [])
            
            if not objs:
                print(f"   ⚠️ Object type '{idf_object_type}' not found in IDF.")
                continue
            
            # Find target object by name
            target_obj = None
            for obj in objs:
                try:
                    obj_name = obj.get("Name", "")
                    if obj_name == target_object_name:
                        target_obj = obj
                        break
                except:
                    continue
            
            if target_obj is None:
                print(f"   ⚠️ Object '{target_object_name}' not found. Using first object as fallback.")
                target_obj = objs[0]
            
            # Apply modification
            try:
                # ✅ Special handling for window geometry
                if param_type == "window_geometry":
                    # Scale window vertices instead of modifying multiplier
                    scale_window_vertices(target_obj, new_value)
                    
                    # Calculate approximate area change
                    area_change_pct = (new_value**2 - 1) * 100  # Area scales with square of linear dimension
                    
                    print(f"      [{idx}] Scaled window vertices to {new_value*100:.0f}% (Area: {area_change_pct:+.1f}%)")
                    print(f"           {description}")
                    
                    change_log.append({
                        "parameter_name": param_name,
                        "variant": idx if len(modifications) > 1 else None,
                        "category": category,
                        "parameter_type": param_type,
                        "object_type": idf_object_type,
                        "object_name": target_object_name,
                        "field": "Vertices (scaled)",
                        "original_value": "100% size",
                        "new_value": f"{new_value*100:.0f}% size",
                        "change_percentage": area_change_pct,
                        "modification_strategy": description,
                        "file": f"modified_{param_name.replace(' ', '_').replace('/', '_')}{'_v' + str(idx) if len(modifications) > 1 else ''}.idf"
                    })
                
                # ✅ Standard field modification for other parameter types
                else:
                    current_value = target_obj[field]
                    
                    # Handle numeric values
                    if isinstance(new_value, (int, float)):
                        # Preserve type
                        if isinstance(current_value, int):
                            new_value = int(round(new_value))
                        else:
                            new_value = round(new_value, 6)
                        
                        target_obj[field] = new_value
                        
                        # Calculate change
                        if isinstance(current_value, (int, float)) and current_value != 0:
                            change_pct = ((new_value - current_value) / abs(current_value)) * 100
                        else:
                            change_pct = 0
                        
                        print(f"      [{idx}] {current_value} → {new_value} ({change_pct:+.1f}%) | {description}")
                    
                    # Handle string values
                    elif isinstance(new_value, str):
                        target_obj[field] = new_value
                        change_pct = None
                        print(f"      [{idx}] '{current_value}' → '{new_value}' | {description}")
                    
                    # Log change
                    change_log.append({
                        "parameter_name": param_name,
                        "variant": idx if len(modifications) > 1 else None,
                        "category": category,
                        "parameter_type": param_type,
                        "object_type": idf_object_type,
                        "object_name": target_object_name,
                        "field": field,
                        "original_value": current_value if isinstance(current_value, (int, float, str)) else str(current_value),
                        "new_value": new_value,
                        "change_percentage": round(change_pct, 2) if change_pct is not None else None,
                        "modification_strategy": description,
                        "file": f"modified_{param_name.replace(' ', '_').replace('/', '_')}{'_v' + str(idx) if len(modifications) > 1 else ''}.idf"
                    })
                
                # Save modified IDF
                if len(modifications) > 1:
                    suffix = f"_v{idx}"
                else:
                    suffix = ""
                
                output_filename = f"modified_{param_name.replace(' ', '_').replace('/', '_')}{suffix}.idf"
                output_path = os.path.join(output_dir, output_filename)
                idf_copy.saveas(output_path)
                modified_paths.append(output_path)
                
            except Exception as e:
                print(f"      ❌ Error: {e}")
                import traceback
                traceback.print_exc()
        
        print(f"   ✅ Generated {len(modifications)} IDF file(s)")

    # ✅ Save logs
    if change_log:
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        
        # JSON log
        log_path = os.path.join(output_dir, f"modification_log_{timestamp}.json")
        with open(log_path, "w", encoding="utf-8") as f:
            json.dump(change_log, f, indent=2, ensure_ascii=False)
        print(f"\n📋 Change log saved: {log_path}")
        
        # Summary report
        summary_path = os.path.join(output_dir, "modification_summary.txt")
        with open(summary_path, "w", encoding="utf-8") as f:
            f.write("=" * 90 + "\n")
            f.write("SMART RULE-BASED IDF MODIFICATION SUMMARY\n")
            f.write("=" * 90 + "\n\n")
            f.write(f"Total Parameters: {len(parameters)}\n")
            f.write(f"Total IDF Files Generated: {len(modified_paths)}\n")
            f.write(f"Timestamp: {timestamp}\n\n")
            
            # Group by parameter type
            type_counts = {}
            for log in change_log:
                ptype = log['parameter_type']
                type_counts[ptype] = type_counts.get(ptype, 0) + 1
            
            f.write("Parameter Type Distribution:\n")
            for ptype, count in sorted(type_counts.items()):
                f.write(f"  • {ptype.upper()}: {count} variants\n")
            f.write("\n" + "=" * 90 + "\n\n")
            
            # Detailed changes
            current_param = None
            for log in change_log:
                if log['parameter_name'] != current_param:
                    current_param = log['parameter_name']
                    f.write(f"\n{'='*90}\n")
                    f.write(f"Parameter: {log['parameter_name']}\n")
                    f.write(f"Type: {log['parameter_type'].upper()} | Category: {log['category']}\n")
                    f.write(f"Object: {log['object_name']}\n")
                    f.write(f"{'='*90}\n")
                
                variant_str = f" [Variant {log['variant']}]" if log['variant'] else ""
                f.write(f"{variant_str}\n")
                f.write(f"  Field: {log['field']}\n")
                f.write(f"  Original: {log['original_value']}\n")
                f.write(f"  Modified: {log['new_value']}\n")
                if log['change_percentage'] is not None:
                    f.write(f"  Change: {log['change_percentage']:+.1f}%\n")
                f.write(f"  Strategy: {log['modification_strategy']}\n")
                f.write(f"  File: {log['file']}\n")
                f.write("\n")
        
        print(f"📄 Summary saved: {summary_path}")

    print("\n" + "=" * 90)
    return modified_paths


if __name__ == "__main__":
    print("🚀 Running Smart Rule-Based Agent 2 Parameter Modifier...\n")

    BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../"))
    output_dir = os.path.join(BASE_DIR, "outputs")
    schema_path = os.path.join(output_dir, "parameter_schema_latest.json")

    print("📂 Using schema:", schema_path)

    if not os.path.exists(schema_path):
        print("⚠️ Latest schema not found, trying to locate timestamped version...")
        schema_path = find_latest_schema(output_dir)
        print(f"✅ Found: {schema_path}\n")

    idf_path = r"sample_files\iUnit_Golden.idf"
    modified_dir = os.path.join(output_dir, "modified_idfs")

    schema = load_json_schema(schema_path)
    modified_files = modify_idf_smart_rules(idf_path, schema, modified_dir)

    print("\n✅ All modified IDF files generated:")
    for i, f in enumerate(modified_files, 1):
        print(f"  {i}. {os.path.basename(f)}")
    
    print(f"\n📊 Total files created: {len(modified_files)}")
    
    # Group by parameter
    param_counts = {}
    for f in modified_files:
        basename = os.path.basename(f)
        param = basename.replace("modified_", "").split("_v")[0]
        param_counts[param] = param_counts.get(param, 0) + 1
    
    print("\n📈 Files per parameter:")
    for param, count in sorted(param_counts.items()):
        print(f"  • {param}: {count} variant(s)")